In [1]:
import pandas as pd

In [2]:
ufos = pd.read_csv('scrubbed.csv', low_memory = False)

In [3]:
ufos.head()

,datetime,city,state,country,shape,duration (seconds),duration (hours/min),comments,date posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [4]:
ufos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80332 entries, 0 to 80331
Data columns (total 11 columns):
datetime                80332 non-null object
city                    80332 non-null object
state                   74535 non-null object
country                 70662 non-null object
shape                   78400 non-null object
duration (seconds)      80332 non-null object
duration (hours/min)    80332 non-null object
comments                80317 non-null object
date posted             80332 non-null object
latitude                80332 non-null object
longitude               80332 non-null float64
dtypes: float64(1), object(10)
memory usage: 6.7+ MB

In [5]:
ufos.shape

(80332, 11)

In [6]:
ufos.columns

Index(['datetime', 'city', 'state', 'country', 'shape', 'duration (seconds)',
       'duration (hours/min)', 'comments', 'date posted', 'latitude',
       'longitude '],
      dtype='object')

In [7]:
ufos.rename(columns = {'duration (seconds)': 'duration_seconds', 'duration (hours/min)': 'duration_hours_min', 'date posted': 'date_posted', 'longitude ': 'longitude'}, inplace = True)

In [8]:
ufos.columns

Index(['datetime', 'city', 'state', 'country', 'shape', 'duration_seconds',
       'duration_hours_min', 'comments', 'date_posted', 'latitude',
       'longitude'],
      dtype='object')

In [29]:
ufos.dtypes

datetime               object
city                   object
state                  object
country                object
shape                  object
duration_seconds       object
duration_hours_min     object
comments               object
date_posted            object
latitude               object
longitude             float64
dtype: object

In [10]:
ufos.head()

,datetime,city,state,country,shape,duration_seconds,duration_hours_min,comments,date_posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.8830556,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.38421,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.2,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.9783333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.4180556,-157.803611

In [11]:
set(ufos['datetime'])

{'11/9/1999 22:49',
 '8/26/2011 00:00',
 '4/3/2005 13:50',
 '10/15/1975 03:00',
 '3/7/2011 18:50',
 '12/15/2007 19:10',
 '1/15/2014 19:45',
 '4/16/2005 17:00',
 '5/29/2012 23:00',
 '12/22/1965 09:00',
 '11/12/2013 19:00',
 '12/21/1998 02:10',
 '4/9/2005 22:50',
 '3/21/2014 15:20',
 '11/17/2008 18:00',
 '9/18/2005 23:30',
 '8/2/2008 02:00',
 '12/6/2008 23:32',
 '3/20/2009 18:59',
 '3/29/2013 21:00',
 '4/5/2008 23:45',
 '1/12/2012 22:00',
 '5/26/2008 22:00',
 '10/24/2008 24:00',
 '3/21/2013 18:00',
 '4/18/2012 12:41',
 '5/27/2012 21:24',
 '6/6/1957 22:00',
 '7/10/2010 23:20',
 '7/15/2005 17:00',
 '9/10/1995 09:30',
 '3/13/2001 19:30',
 '10/29/2000 18:45',
 '12/8/2011 01:13',
 '5/4/2010 21:30',
 '3/1/2007 19:10',
 '12/31/2010 16:26',
 '10/6/1999 22:46',
 '11/18/2000 19:30',
 '7/1/1985 20:30',
 '7/19/2002 19:50',
 '10/15/2007 22:30',
 '11/4/2009 18:00',
 '12/16/2009 06:30',
 '7/12/1997 02:45',
 '6/20/2009 23:00',
 '9/6/2008 21:10',
 '10/7/2009 18:40',
 '2/24/2003 11:30',
 '7/26/2013 21:15',
 '12/1/2000 04:35',
 '6/26/2012 23:00',
 '1/22/2003 21:30',
 '8/8/2011 00:22',
 '9/10/1967 00:00',
 '10/26/2005 21:30',
 '8/15/2013 19:45',
 '10/30/2006 19:10',
 '7/27/2013 21:50',
 '4/5/1980 24:00',
 '12/25/2002 21:45',
 '9/25/2001 21:45',
 '6/26/2004 22:30',
 '7/12/2009 21:55',
 '8/18/2002 23:51',
 '11/8/2004 18:00',
 '4/15/1992 19:30',
 '5/21/1992 20:34',
 '5/8/2008 23:25',
 '7/13/2013 22:45',
 '7/12/2003 23:00',
 '11/4/2012 10:45',
 '2/18/2009 12:00',
 '9/20/2004 13:40',
 '10/9/2001 21:15',
 '1/15/1997 17:30',
 '2/27/2010 22:34',
 '7/15/1987 23:00',
 '8/4/2008 22:10',
 '9/19/2002 19:00',
 '6/15/2005 02:30',
 '6/9/2011 11:00',
 '4/15/1998 17:44',
 '4/3/2013 12:30',
 '9/12/2008 21:25',
 '1/3/2007 18:15',
 '5/28/2012 08:15',
 '2/15/2009 15:45',
 '6/9/2013 22:30',
 '10/20/2004 21:30',
 '6/1/1975 18:00',
 '7/6/2004 22:00',
 '8/26/2006 09:00',
 '10/20/1999 22:25',
 '12/2/2010 15:15',
 '10/31/1981 18:00',
 '11/13/2013 01:30',
 '6/30/2008 05:45',
 '2/9/2002 14:00',
 '12/19/1999 18:30',
 '12/19/2009 01:45',
 '6/30/1958 16:00',
 '5/19/2001 00:01',
 '4/4/2006 21:22',
 '11/11/2012 22:00',
 '12/5/2010 23:00',
 '2/9/2006 18:35',
 '7/16/2011 22:00',
 '8/17/2004 20:00',
 '7/30/2007 01:30',
 '7/7/1997 12:00',
 '9/15/1998 20:30',
 '2/18/2013 06:02',
 '3/28/1996 19:40',
 '7/15/1990 14:00',
 '11/10/1999 23:00',
 '4/21/2004 00:40',
 '11/8/2012 19:00',
 '2/26/2008 21:00',
 '5/31/2012 00:30',
 '9/15/2007 23:00',
 '2/3/1997 20:00',
 '4/21/1999 21:45',
 '3/24/2004 23:23',
 '9/22/2007 00:45',
 '1/17/2002 16:00',
 '8/5/2006 13:00',
 '1/28/2009 02:45',
 '2/7/2014 03:50',
 '6/9/2001 21:00',
 '8/15/2003 18:50',
 '9/3/2004 19:30',
 '2/17/2014 22:30',
 '10/14/2011 18:30',
 '3/20/2014 20:00',
 '11/4/2013 22:00',
 '10/16/2013 21:20',
 '1/15/2011 23:30',
 '6/30/1956 13:00',
 '8/1/2001 04:00',
 '7/6/2009 21:10',
 '8/22/2012 05:20',
 '1/28/2007 17:00',
 '1/20/2004 21:00',
 '5/20/2005 03:00',
 '7/8/2012 21:30',
 '9/24/2008 23:00',
 '9/4/2004 20:00',
 '10/15/2007 21:30',
 '10/18/2012 22:00',
 '12/20/2011 08:50',
 '10/18/1990 01:00',
 '5/13/2001 23:30',
 '11/11/2011 20:45',
 '6/15/1998 20:30',
 '10/24/2013 04:45',
 '11/15/1999 17:00',
 '12/9/2012 09:55',
 '10/19/2013 21:30',
 '9/14/2009 22:30',
 '5/27/2009 04:00',
 '6/15/1958 19:15',
 '7/17/2009 22:45',
 '7/9/2005 22:45',
 '11/7/2008 05:30',
 '8/2/2005 21:00',
 '6/6/1999 03:40',
 '2/18/2005 10:01',
 '2/24/2007 10:30',
 '10/6/2011 20:41',
 '1/29/2011 20:30',
 '3/19/2007 09:22',
 '5/5/2013 16:00',
 '9/9/2011 08:30',
 '1/9/2013 05:30',
 '7/7/1997 14:30',
 '10/1/2003 22:30',
 '8/17/2013 20:55',
 '1/13/2012 19:40',
 '7/21/2007 04:25',
 '10/6/2008 21:10',
 '8/15/2008 14:00',
 '10/16/2008 00:55',
 '9/8/2012 12:30',
 '12/11/2000 22:45',
 '12/24/2010 22:30',
 '3/8/2012 19:35',
 '9/14/2000 07:51',
 '12/13/2011 13:30',
 '7/12/2012 21:30',
 '9/5/1975 20:00',
 '8/23/2011 03:00',
 '6/20/1976 00:00',
 '10/22/1985 20:00',
 '1/1/2012 00:11',
 '3/31/2009 00:11',
 '7/19/2009 01:20',
 '7/31/2006 21:00',
 '1/7/2006 02:40',
 '1/20/2004 00:15',
 '7/16/2010 01:00',
 '2/9/1993 19:30',
 '1/28/2014 19:00',
 '10/15/2000 03:00',
 '10/30/2008 05:15',
 '6/30/2001 10:45',
 '4/21/2007 14:35',
 '7/2/2011 18:00',
 '10/20/2011 21:30',
 '11/19/2012 13:00',
 '7/18/2012 16:00',
 '8/23/2011 11:06',
 '9/4/2005 21:00',
 '2/16/2010 22:15',
 '9/17/2013 20:00',
 '8/21/2012 23:15',
 '12/10/2010 20:00',
 '4/30/2004 03:00',
 '7/14/2008 03:20',
 '6/18/2011 00:00',
 '7/24/1999 00:25',
 '7/7/2006 20:15',
 '5/3/2014 23:30',
 '9/4/1998 20:45',
 '11/5/2005 22:50',
 '10/9/2012 02:20',
 '7/19/2009 22:20',
 '7/18/1990 22:00',
 '6/22/2000 23:00',
 '6/28/2010 22:30',
 '5/1/2001 04:30',
 '8/14/2002 16:00',
 '7/30/2009 00:30',
 '10/21/2013 08:10',
 '12/2/2011 21:00',
 '6/15/1974 08:00',
 '8/20/1965 22:00',
 '6/10/1988 22:30',
 '3/29/2003 21:00',
 '7/3/2013 22:00',
 '2/4/2002 21:30',
 '3/25/2011 07:00',
 '10/23/2003 23:00',
 '5/24/2013 23:00',
 '9/7/2006 18:20',
 '7/7/1962 02:00',
 '8/31/2003 19:00',
 '11/2/1999 19:15',
 '1/7/2008 07:00',
 '3/28/1998 20:30',
 '7/15/2001 04:19',
 '5/21/1995 23:20',
 '7/15/2007 00:45',
 '10/8/2012 21:30',
 '8/10/1979 21:45',
 '1/17/2014 11:00',
 '9/20/2008 23:45',
 '6/19/2007 23:05',
 '6/15/2004 05:00',
 '6/30/2004 21:00',
 '12/1/1974 20:30',
 '2/27/2008 00:12',
 '5/30/2013 20:00',
 '2/28/2000 21:30',
 '11/14/2011 23:00',
 '8/30/2001 18:00',
 '5/2/2004 00:01',
 '7/4/2004 23:00',
 '11/1/2001 13:00',
 '3/3/2009 03:00',
 '4/24/2014 21:30',
 '1/1/2014 17:00',
 '11/25/2009 20:15',
 '5/1/1977 01:00',
 '1/29/2014 21:00',
 '4/6/2010 20:57',
 '6/30/1984 08:30',
 '7/18/2009 21:00',
 '3/21/2005 20:30',
 '7/4/2009 23:59',
 '8/11/2003 18:30',
 '4/2/2009 11:30',
 '1/21/2003 19:45',
 '12/10/2002 07:45',
 '2/14/2009 19:45',
 '2/5/2001 23:10',
 '4/22/1998 22:00',
 '4/21/2004 22:00',
 '1/3/2012 07:00',
 '12/22/2011 18:00',
 '3/20/2011 20:00',
 '5/24/1999 21:55',
 '5/4/2012 18:15',
 '6/10/2002 00:00',
 '7/28/2013 00:45',
 '12/25/2006 18:30',
 '1/27/2006 01:00',
 '11/27/2006 14:15',
 '9/22/2010 22:30',
 '10/4/2007 22:00',
 '12/2/2010 21:30',
 '6/10/1998 22:00',
 '5/29/2011 17:00',
 '6/20/1980 20:00',
 '9/23/2002 20:50',
 '12/24/2013 20:40',
 '7/23/2004 02:00',
 '7/31/2010 24:00',
 '7/11/2005 00:56',
 '4/28/2011 17:57',
 '7/1/2003 02:30',
 '9/20/1988 03:00',
 '5/14/2007 21:00',
 '8/14/2005 03:00',
 '2/18/2002 22:00',
 '11/29/2004 05:20',
 '6/18/1996 17:30',
 '8/30/2002 13:45',
 '11/25/2013 21:45',
 '3/21/2014 20:40',
 '11/15/2003 00:00',
 '8/16/2010 22:16',
 '3/31/2001 20:00',
 '1/27/1998 20:20',
 '6/29/2013 21:38',
 '10/6/2004 22:30',
 '8/27/2010 22:17',
 '10/18/2001 00:00',
 '4/8/2012 10:56',
 '4/14/2012 22:00',
 '6/7/2012 01:05',
 '7/19/2006 21:00',
 '7/17/2007 19:30',
 '6/15/2002 22:00',
 '3/8/2005 23:30',
 '12/17/2011 00:50',
 '8/10/2003 02:00',
 '10/13/2007 11:15',
 '7/18/2009 02:00',
 '7/23/1996 22:30',
 '8/17/2013 22:08',
 '3/20/2002 20:50',
 '12/9/1999 21:50',
 '6/19/2002 19:00',
 '8/31/2002 17:43',
 '9/12/2002 03:00',
 '7/3/1995 10:30',
 '2/15/2014 20:45',
 '3/9/2001 03:36',
 '9/20/2013 04:40',
 '8/9/1997 11:24',
 '4/11/2012 22:07',
 '8/13/2004 07:30',
 '5/30/2009 23:00',
 '8/7/1996 23:00',
 '9/14/2013 19:40',
 '2/17/2008 17:00',
 '3/26/2013 20:10',
 '8/10/2000 22:00',
 '8/1/2003 00:15',
 '8/6/2005 18:55',
 '7/20/2001 14:30',
 '1/15/2008 18:00',
 '4/14/2005 21:30',
 '9/1/2007 21:00',
 '11/21/2008 20:10',
 '1/10/2011 05:30',
 '6/6/2013 03:30',
 '10/28/2008 20:20',
 '1/11/2001 09:06',
 '11/14/2009 17:45',
 '4/23/2014 22:15',
 '1/22/2013 05:25',
 '7/3/2007 18:45',
 '1/4/2014 21:00',
 '11/1/2013 18:00',
 '4/1/1978 04:00',
 '8/16/2006 20:30',
 '9/26/2008 18:00',
 '9/2/2011 19:00',
 '7/27/2013 11:30',
 '8/29/2007 11:34',
 '9/29/2006 24:00',
 '6/27/2013 20:30',
 '5/1/1996 22:00',
 '8/23/2013 08:20',
 '11/24/2005 18:30',
 '10/18/2013 19:00',
 '4/27/2009 21:00',
 '6/1/1960 20:00',
 '9/22/2006 04:30',
 '12/29/2007 15:00',
 '5/15/2002 16:00',
 '9/22/2006 04:00',
 '7/5/2011 22:40',
 '4/3/2014 21:00',
 '12/28/2013 11:00',
 '4/12/2002 22:00',
 '3/15/2004 19:45',
 '7/4/1965 20:00',
 '3/13/2006 22:30',
 '10/29/2012 19:41',
 '3/4/2007 11:00',
 '5/10/2001 17:00',
 '11/11/2001 19:00',
 '6/15/1979 15:00',
 '6/29/2002 02:25',
 '7/30/2011 21:20',
 '1/9/2006 18:53',
 '3/11/2000 22:45',
 '7/26/2012 19:35',
 '5/15/1989 20:00',
 '4/18/2012 20:55',
 '6/6/1998 19:30',
 '8/30/1988 06:00',
 '10/12/1973 19:00',
 '2/27/2014 14:50',
 '9/15/1990 22:30',
 '9/22/2008 19:55',
 '11/30/2009 20:51',
 '6/1/1973 19:30',
 '8/7/2008 23:00',
 '9/20/1995 18:30',
 '11/25/1985 00:00',
 '10/28/1998 20:00',
 '1/3/2013 05:50',
 '2/20/1987 01:30',
 '1/13/2011 17:31',
 '11/28/2013 21:00',
 '8/26/2004 22:13',
 '6/15/2001 22:20',
 '12/24/2003 06:45',
 '8/30/2008 17:00',
 '3/15/1979 19:00',
 '8/18/2000 22:08',
 '10/6/2012 21:30',
 '1/11/2001 23:20',
 '12/7/2007 20:00',
 '10/3/2005 22:30',
 '11/5/2010 22:30',
 '5/18/2010 21:55',
 '9/25/2003 21:00',
 '12/21/2003 22:00',
 '10/23/2010 16:21',
 '9/27/2004 20:43',
 '9/19/2002 02:30',
 '12/27/2000 22:10',
 '4/14/2006 19:15',
 '9/10/1998 07:15',
 '9/4/2005 24:00',
 '3/5/2004 20:00',
 '6/23/2012 13:00',
 '1/20/2009 19:45',
 '3/20/2010 00:29',
 '5/7/2002 20:55',
 '8/23/2000 19:49',
 '10/5/2008 21:00',
 '4/14/2002 03:00',
 '9/28/1998 16:00',
 '12/7/2012 21:49',
 '9/5/2008 23:00',
 '11/6/1999 01:30',
 '10/26/2000 21:30',
 '3/26/2014 03:00',
 '8/4/2004 16:19',
 '11/17/1999 03:00',
 '2/4/2001 21:30',
 '6/12/2010 21:50',
 '12/1/2013 18:00',
 '9/2/2007 10:50',
 '2/8/2014 08:12',
 '3/15/2006 22:40',
 '2/15/2011 23:26',
 '9/22/2007 21:00',
 '10/10/2013 20:30',
 '10/8/2000 05:45',
 '7/4/2005 21:03',
 '10/3/2009 22:00',
 '4/6/2014 20:30',
 '6/21/2008 22:00',
 '4/4/2014 21:40',
 '5/30/2008 11:00',
 '7/27/2009 03:30',
 '4/8/2014 20:45',
 '7/8/2013 11:20',
 '6/10/2010 05:00',
 '9/2/2013 18:50',
 '8/28/1997 20:00',
 '3/5/2011 05:55',
 '12/1/2011 00:10',
 '2/11/2004 05:45',
 '4/22/2004 00:10',
 '10/1/2013 12:40',
 '7/4/2005 21:45',
 '11/5/2005 01:00',
 '5/3/2005 12:00',
 '12/31/2007 22:40',
 '6/16/2008 01:00',
 '8/15/1955 00:01',
 '11/14/2003 22:30',
 '9/24/2013 21:45',
 '1/30/1974 23:00',
 '4/9/2011 19:30',
 '8/4/1994 22:00',
 '2/24/2011 19:50',
 '2/25/2005 05:30',
 '8/23/2009 14:53',
 '11/5/2005 18:30',
 '8/24/2007 17:30',
 '4/28/2012 19:00',
 '6/16/2013 12:00',
 '7/3/2002 03:10',
 '7/9/2000 12:00',
 '10/16/2007 14:25',
 '7/29/2013 01:00',
 '1/8/2007 11:00',
 '11/18/2011 19:40',
 '5/15/2007 17:30',
 '12/14/2007 19:15',
 '7/31/2012 01:22',
 '6/6/2010 01:35',
 '1/4/2014 20:35',
 '7/20/2003 11:00',
 '5/1/2001 17:30',
 '3/7/1998 18:17',
 '8/23/2007 03:35',
 '11/19/2002 18:45',
 '1/22/2010 22:30',
 '10/17/2008 23:00',
 '12/10/2010 23:00',
 '4/18/2014 12:00',
 '6/9/1997 22:30',
 '6/25/2012 22:00',
 '3/17/2011 19:00',
 '10/15/1997 20:15',
 '12/15/2013 20:08',
 '10/3/2013 21:23',
 '2/2/2012 13:00',
 '4/27/2012 23:27',
 '12/3/2013 19:15',
 '8/26/2002 12:15',
 '2/11/2004 16:00',
 '11/1/2003 11:04',
 '10/10/2003 20:05',
 '7/15/2006 22:05',
 '7/4/1969 10:30',
 '8/29/2011 08:45',
 '9/4/2004 06:00',
 '10/15/1968 07:30',
 '6/16/2011 23:20',
 '3/22/2011 19:30',
 '9/5/2012 01:00',
 '12/29/2013 22:50',
 '11/30/1998 20:00',
 '6/30/1996 22:00',
 '5/13/2004 21:00',
 '11/8/2013 22:00',
 '1/5/2006 21:30',
 '7/15/1983 18:30',
 '10/3/2008 11:15',
 '9/11/2006 00:30',
 '9/5/2004 23:10',
 '8/6/2003 18:30',
 '12/20/2007 06:52',
 '8/17/2013 21:10',
 '10/5/2013 22:00',
 '11/8/2006 19:00',
 '9/12/2012 20:50',
 '9/20/1958 22:20',
 '9/19/2009 03:00',
 '10/19/2012 02:00',
 '9/15/2012 20:30',
 '12/9/2007 18:00',
 '10/30/2012 19:00',
 '11/20/1996 19:00',
 '8/2/2007 21:15',
 '1/3/2005 00:35',
 '8/19/2006 05:11',
 '8/21/2001 21:15',
 '7/4/1997 21:15',
 '9/11/2004 03:00',
 '10/5/2006 10:30',
 '6/12/2001 01:00',
 '3/28/2007 22:30',
 '9/19/2013 19:39',
 '4/18/1997 20:40',
 '5/31/2012 22:00',
 '9/17/2008 20:30',
 '7/23/2011 02:42',
 '7/19/2002 11:35',
 '9/11/2011 23:00',
 '8/31/2013 20:35',
 '6/1/1999 11:30',
 '6/10/1999 00:00',
 '11/1/2013 17:30',
 '3/19/2011 23:45',
 '10/17/2004 21:15',
 '9/21/2013 06:00',
 '5/26/2013 21:30',
 '7/20/2011 21:00',
 '7/13/2005 00:20',
 '1/2/2013 01:45',
 '1/16/2014 18:00',
 '12/12/2004 19:00',
 '10/31/2004 21:30',
 '1/10/2005 22:00',
 '12/1/2001 22:00',
 '1/15/1997 18:00',
 '10/10/2007 20:24',
 '10/29/2012 22:00',
 '4/15/2010 22:18',
 '12/31/2010 23:25',
 '6/30/1968 21:00',
 '3/6/2007 20:38',
 '8/5/2009 05:45',
 '8/26/2001 12:15',
 '5/20/1995 22:00',
 '2/28/2008 22:02',
 '11/9/2005 20:30',
 '2/8/2007 19:50',
 '4/10/2001 16:30',
 '10/11/2013 21:00',
 '1/15/2005 22:00',
 '2/9/2011 19:10',
 '3/27/1977 00:00',
 '7/4/2009 21:49',
 '8/18/1994 00:00',
 '10/31/2013 14:23',
 '4/4/2011 04:00',
 '7/5/2010 22:15',
 '11/17/2011 23:00',
 '8/20/2008 03:00',
 '2/10/2011 21:30',
 '4/18/2010 13:33',
 '1/28/2011 21:00',
 '5/6/2001 21:30',
 '1/15/1998 13:00',
 '4/13/2004 00:00',
 '4/8/2006 23:00',
 '8/12/1993 21:00',
 '1/1/2013 00:38',
 '8/10/2012 23:00',
 '1/25/2013 20:35',
 '8/5/2006 00:00',
 '7/17/2007 18:54',
 '6/20/1995 09:30',
 '5/23/2002 20:09',
 '11/23/2005 00:45',
 '10/9/1999 00:33',
 '5/17/2013 21:19',
 '2/24/2005 17:56',
 '11/5/2013 21:28',
 '6/27/2006 00:15',
 '9/15/2001 20:22',
 '11/7/2006 21:00',
 '1/8/2008 07:30',
 '8/4/2006 21:45',
 '8/23/2011 16:00',
 '11/1/1978 10:00',
 '12/15/2012 06:55',
 '2/26/2012 22:45',
 '2/6/2006 03:30',
 '9/15/2012 21:15',
 '9/24/1998 01:30',
 '10/26/1998 18:05',
 '2/27/2014 22:55',
 '11/15/2003 20:13',
 '6/3/2009 00:00',
 '3/30/2005 19:30',
 '7/13/2006 23:45',
 '7/27/1999 23:00',
 '11/4/2012 19:00',
 '11/19/1998 22:15',
 '8/13/2011 21:13',
 '8/15/1988 01:00',
 '5/18/2009 09:40',
 '7/10/2003 21:00',
 '5/29/1998 05:00',
 '9/17/2005 02:30',
 '10/31/2009 23:00',
 '6/1/1998 21:00',
 '7/3/2003 22:47',
 '10/15/2002 20:30',
 '2/17/2008 10:00',
 '8/31/2013 22:20',
 '2/14/2011 12:35',
 '1/15/1979 20:00',
 '4/14/2010 02:30',
 '8/12/2011 07:45',
 '6/24/2013 22:03',
 '7/3/2007 22:20',
 '2/15/1998 23:35',
 '11/15/1992 20:00',
 '12/5/2012 12:30',
 '5/30/2012 19:30',
 '12/12/2002 21:05',
 '3/19/2001 13:00',
 '5/23/2004 23:00',
 '8/9/2004 10:30',
 '12/17/2012 17:30',
 '3/9/2005 23:45',
 '4/19/1995 21:45',
 '6/2/2001 18:00',
 '11/1/2013 07:30',
 '12/16/2010 19:40',
 '12/8/2013 18:20',
 '9/28/2008 00:15',
 '9/28/2013 21:45',
 '8/15/2006 23:00',
 '5/14/2004 22:30',
 '7/10/2010 13:30',
 '4/15/1994 21:00',
 '4/14/2013 20:07',
 '4/18/2014 20:50',
 '6/5/2013 22:05',
 '10/23/2013 22:30',
 '7/8/2011 00:00',
 '2/1/2012 23:00',
 '8/10/2013 22:45',
 '11/2/2005 22:00',
 '8/11/2010 01:00',
 '10/5/2004 20:00',
 '8/19/2001 11:00',
 '12/8/2005 15:00',
 '12/26/2009 16:35',
 '11/25/2009 22:45',
 '8/28/2000 22:15',
 '10/18/1995 18:45',
 '4/9/2007 08:30',
 '6/30/2006 18:00',
 '3/12/2002 20:15',
 '7/21/2006 15:52',
 '6/15/2008 19:00',
 '3/17/2009 21:00',
 '10/20/1975 03:15',
 '7/1/2000 03:00',
 '12/28/2011 17:50',
 '5/15/2009 02:00',
 '8/16/1999 22:40',
 '8/31/2008 23:00',
 '9/30/2011 12:19',
 '2/22/2005 20:00',
 '10/19/2011 23:30',
 '4/21/2006 21:05',
 '8/14/2013 19:00',
 '9/2/2011 22:15',
 '11/11/2006 22:00',
 '9/25/1995 06:01',
 '1/10/2000 22:00',
 '2/29/2004 16:00',
 '3/6/2006 20:30',
 '6/20/2002 20:15',
 '2/19/2013 23:30',
 '11/12/2010 05:30',
 '7/29/2012 01:00',
 '8/18/2002 23:00',
 '7/27/2010 19:30',
 '10/10/2008 04:50',
 '2/7/2001 14:23',
 '5/30/1991 09:10',
 '2/1/2011 17:30',
 '2/16/1999 06:45',
 '2/2/2003 19:00',
 '10/17/2003 22:00',
 '6/30/2013 22:50',
 '7/11/2006 20:30',
 '7/4/2012 21:20',
 '8/9/2013 21:45',
 '11/30/2002 20:50',
 '8/16/2004 22:15',
 '5/6/2006 01:00',
 '5/30/2012 22:30',
 '1/22/2005 20:00',
 '4/9/2014 04:00',
 '9/6/2013 16:00',
 '7/8/2006 01:45',
 '3/13/2006 22:00',
 '10/1/2008 22:00',
 '1/31/2001 23:45',
 '3/1/2000 21:00',
 '3/1/2005 20:05',
 '4/6/2011 21:20',
 '3/22/2004 19:00',
 '6/7/2013 21:00',
 '7/27/2011 11:45',
 '10/27/2009 06:00',
 '8/12/2012 03:15',
 '8/8/2013 21:11',
 '9/7/2010 22:30',
 '10/6/2011 22:05',
 '11/2/2011 15:50',
 '5/20/2000 16:10',
 '7/10/1989 00:00',
 '11/4/2013 22:25',
 '4/24/2011 17:30',
 '10/24/2013 20:35',
 '6/16/2008 22:00',
 '8/12/2012 23:00',
 '2/15/2009 11:30',
 '12/11/2006 22:53',
 '3/17/2007 08:00',
 '7/12/2008 22:30',
 '10/15/2005 21:25',
 '7/15/1972 23:00',
 '7/8/2004 23:00',
 '1/8/2006 14:00',
 '7/9/2011 21:40',
 '1/19/2007 23:45',
 '12/18/1993 13:00',
 '1/18/2007 22:55',
 '11/27/2012 20:15',
 '2/17/2006 05:48',
 '5/25/2008 19:45',
 '7/30/2005 21:09',
 '7/22/1968 22:00',
 '5/25/1996 23:00',
 '11/3/2008 00:00',
 '1/23/2006 03:00',
 '8/18/2012 12:43',
 '10/3/2012 11:30',
 '12/2/2013 05:30',
 '10/4/2008 21:26',
 '9/11/2008 21:15',
 '8/3/2013 21:40',
 '6/15/2000 22:00',
 '11/14/1999 22:05',
 '1/14/2007 16:00',
 '4/6/1978 20:00',
 '5/26/2012 05:45',
 '2/3/2002 18:15',
 '6/12/1985 11:00',
 '8/19/2004 17:00',
 '1/1/1962 08:00',
 '3/24/2007 06:30',
 '8/28/2003 06:10',
 '8/7/1994 22:30',
 '2/4/2001 23:58',
 '4/2/2000 18:00',
 '2/12/2003 06:35',
 '7/6/2012 21:55',
 '2/21/2005 20:35',
 '2/24/2009 01:30',
 '1/1/2005 17:30',
 '11/29/2007 19:15',
 '4/20/1983 00:00',
 '9/17/2003 10:00',
 '8/28/2006 22:00',
 '9/7/2013 07:45',
 '6/18/2012 21:50',
 '12/25/1994 23:00',
 '1/1/2014 18:30',
 '10/11/2006 20:45',
 '1/28/1973 23:38',
 '3/16/2008 23:16',
 '12/13/2011 16:00',
 '7/26/1999 22:00',
 '2/11/2004 19:30',
 '7/16/2002 22:00',
 '10/4/2001 20:00',
 '4/4/1979 06:00',
 '8/30/2003 23:00',
 '3/1/1973 10:30',
 '7/17/2009 00:00',
 '3/17/2012 15:00',
 '4/7/1999 22:58',
 '5/12/2012 20:30',
 '6/3/2000 22:00',
 '4/23/2007 08:00',
 '1/19/2004 21:00',
 '10/18/2010 16:00',
 '10/15/2002 22:00',
 '6/21/2013 01:15',
 '5/6/2006 07:45',
 '12/1/1956 23:00',
 '11/24/2008 17:00',
 '4/10/1998 21:00',
 '9/29/2010 20:45',
 '8/8/2012 23:00',
 '10/19/2005 02:00',
 '12/18/2006 20:00',
 '3/12/2009 16:15',
 '4/15/2008 12:00',
 '1/20/2014 20:05',
 '8/1/1993 23:00',
 '9/18/2012 06:35',
 '9/8/2011 19:05',
 '3/30/2001 09:28',
 '4/8/2012 00:32',
 '1/23/2011 04:30',
 '8/12/2013 19:00',
 '10/29/2005 00:30',
 '12/9/2006 06:11',
 '10/16/2012 19:11',
 '3/26/2009 09:25',
 '3/13/2009 19:10',
 '3/8/2014 05:18',
 '8/24/2009 21:50',
 '8/5/2005 22:25',
 '8/25/2001 05:20',
 '9/12/2011 04:38',
 '6/24/1998 22:00',
 '3/25/2001 11:00',
 '8/10/1966 03:30',
 '5/10/2007 21:00',
 '12/25/2011 04:54',
 '8/1/1998 20:45',
 '10/20/2005 21:10',
 '1/1/2001 01:00',
 '6/17/2013 22:30',
 '4/18/2014 01:17',
 '7/12/1987 15:00',
 '2/28/2012 18:00',
 '1/13/2014 13:45',
 '3/13/2004 02:30',
 '5/15/2012 22:00',
 '11/30/2003 20:45',
 '12/31/2010 22:45',
 '7/1/1999 15:00',
 '2/23/2014 19:45',
 '6/15/1985 23:00',
 '5/25/2013 18:40',
 '3/20/2009 19:00',
 '8/4/2009 23:10',
 '1/8/2008 01:00',
 '6/30/1974 22:00',
 '7/10/1997 13:00',
 '7/1/2009 07:00',
 '11/21/2008 19:30',
 '4/4/1980 22:00',
 '10/4/2006 19:00',
 '9/29/2000 19:40',
 '10/16/2009 22:35',
 '12/17/2011 19:50',
 '12/9/2012 16:00',
 '9/27/1999 20:30',
 '4/21/2005 04:50',
 '7/20/1990 22:00',
 '11/10/1998 22:00',
 '11/15/1962 14:00',
 '8/10/2012 21:30',
 '8/24/2009 21:45',
 '4/25/1996 21:30',
 '12/16/1997 19:55',
 '9/7/2009 00:00',
 '5/15/2004 21:37',
 '12/15/1995 20:50',
 '12/1/2011 07:30',
 '2/28/2013 21:30',
 '12/25/2003 19:06',
 '5/14/2013 01:15',
 '10/13/2000 19:14',
 '4/26/2013 22:10',
 '7/5/1990 17:00',
 '10/1/1980 20:00',
 '8/10/2008 05:50',
 '8/17/2008 22:45',
 '7/28/2006 15:00',
 '11/24/2005 22:30',
 '1/16/2014 19:00',
 '9/23/2013 02:00',
 '10/16/2005 19:48',
 '4/24/2005 22:45',
 '12/28/2012 17:00',
 '1/4/1999 20:24',
 '1/17/2008 02:04',
 '7/29/2002 20:00',
 '7/26/2003 01:20',
 '9/28/2013 20:30',
 '1/28/2000 07:30',
 '6/3/2004 23:30',
 '9/18/2013 23:50',
 '9/2/2009 20:00',
 '8/14/2004 00:30',
 '7/15/1977 01:00',
 '11/8/2012 17:00',
 '2/25/2009 18:05',
 '11/17/2002 10:00',
 '9/30/2006 22:00',
 '10/13/2010 18:15',
 '12/27/2011 19:00',
 '2/26/2002 20:00',
 '4/25/2007 07:30',
 '9/25/2003 22:30',
 '10/9/2009 19:52',
 '12/21/2011 05:30',
 '8/16/2013 00:00',
 '11/16/1999 18:00',
 '12/5/2008 23:00',
 '6/28/2006 11:15',
 '4/17/2011 21:00',
 '7/30/2003 02:30',
 '9/29/2001 20:10',
 '10/7/2000 01:15',
 '1/9/2013 18:00',
 '3/19/2014 00:40',
 '6/1/1992 23:30',
 '9/14/2008 10:40',
 '5/19/2004 21:30',
 '9/25/1999 00:45',
 '11/8/2002 02:00',
 ...}

In [12]:
ufos.astype({'datetime': 'datetime64[ns]', 'date_posted':'datetime64[ns]', 'duration_seconds': int, 'latitude': float})

ValueError: hour must be in 0..23

In [ ]:
ufos.astype({ 'duration_seconds': float})

In [ ]:
ufos.astype({ 'latitude': float})

In [ ]:
ufos.astype({'date_posted' :'datetime64[ns]'}, inplace = True)

In [65]:
ufos['date_posted'] = ufos['date_posted'].astype('datetime64[ns]')

# Latitude

In [ ]:
ufos.astype({ 'latitude': float})

In [ ]:
ufos[ufos['latitude'] == '33.200088']

In [13]:
ufos[ufos['latitude'] == '33q.200088']['latitude'] = '33.200088'

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [14]:
ufos.loc[43782, 'latitude'] = '33.200088'

In [30]:
ufos.astype({ 'latitude': float}, inplace = True)

,datetime,city,state,country,shape,duration_seconds,duration_hours_min,comments,date_posted,latitude,longitude
0,10/10/1949 20:30,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111
1,10/10/1949 21:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.384210,-98.581082
2,10/10/1955 17:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.200000,-2.916667
3,10/10/1956 21:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833
4,10/10/1960 20:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611
5,10/10/1961 19:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595000,-82.188889
6,10/10/1965 21:00,penarth (uk/wales),NaN,gb,circle,180,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2/14/2006,51.434722,-3.180000
7,10/10/1965 23:45,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.117500,-73.408333
8,10/10/1966 20:00,pell city,al,us,disk,180,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.586111,-86.286111
9,10/10/1966 21:00,live oak,fl,us,disk,120,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.294722,-82.984167
10,10/10/1968 13:00,hawthorne,ca,us,circle,300,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...,10/31/2003,33.916389,-118.351667
11,10/10/1968 19:00,brevard,nc,us,fireball,180,3 minutes,silent red /orange mass of energy floated by t...,6/12/2008,35.233333,-82.734444
12,10/10/1970 16:00,bellmore,ny,us,disk,1800,30 min.,silver disc seen by family and neighbors,5/11/2000,40.668611,-73.527500
13,10/10/1970 19:00,manchester,ky,us,unknown,180,3 minutes,Slow moving&#44 silent craft accelerated at an...,2/14/2008,37.153611,-83.761944
14,10/10/1971 21:00,lexington,nc,us,oval,30,30 seconds,green oval shaped light over my local church&#...,2/14/2010,35.823889,-80.253611
15,10/10/1972 19:00,harlan county,ky,us,circle,1200,20minutes,On october 10&#44 1972 myself&#44my 5yrs.daugh...,9/15/2005,36.843056,-83.321944
16,10/10/1972 22:30,west bloomfield,mi,us,disk,120,2 minutes,The UFO was so close&#44 my battery in the car...,8/14/2007,42.537778,-83.233056
17,10/10/1973 19:00,niantic,ct,us,disk,1800,20-30 min,Oh&#44 what a night &#33 Two (2) saucer-shape...,9/24/2003,41.325278,-72.193611
18,10/10/1973 23:00,bermuda nas,NaN,NaN,light,20,20 sec.,saw fast moving blip on the radar scope thin w...,1/11/2002,32.364167,-64.678611
19,10/10/1974 19:30,hudson,ma,us,other,2700,45 minutes,Not sure of the eact month or year of this sig...,8/10/1999,42.391667,-71.566667
20,10/10/1974 21:30,cardiff (uk/wales),NaN,gb,disk,1200,20 minutes,back in 1974 I was 19 at the time and lived i...,2/1/2007,51.500000,-3.200000
21,10/10/1974 23:00,hudson,ks,us,light,1200,one hour?,The light chased us.,7/25/2004,38.105556,-98.659722
22,10/10/1975 17:00,north charleston,sc,us,light,360,5-6 minutes,Several Flashing UFO lights over Charleston Na...,2/14/2008,32.854444,-79.975000
23,10/10/1976 20:30,washougal,wa,us,oval,60,1 minute,Three extremely large lights hanging above nea...,2/7/2014,45.582778,-122.352222
24,10/10/1976 22:00,stoke mandeville (uk/england),NaN,gb,cigar,3,3 seconds,White object over Buckinghamshire UK.,12/12/2009,51.783333,-0.783333
25,10/10/1977 12:00,san antonio,tx,us,other,30,30 seconds,i was about six or seven and my family and me ...,2/24/2005,29.423889,-98.493333
26,10/10/1977 22:00,louisville,ky,us,light,30,approx: 30 seconds,HBCCUFO CANADIAN REPORT: Pilot Sighting Of Un...,3/17/2004,38.254167,-85.759444
27,10/10/1978 02:00,elmont,ny,us,rectangle,300,5min,A memory I will never forget that happened men...,2/1/2007,40.700833,-73.713333
28,10/10/1979 00:00,poughkeepsie,ny,us,chevron,900,15 minutes,1/4 moon-like&#44 its &#39chord&#39 or flat s...,4/16/2005,41.700278,-73.921389
29,10/10/1979 22:00,saddle lake (canada),ab,NaN,triangle,270,4.5 or more min.,Lights far above&#44 that glance; then flee f...,1/19/2005,53.970571,-111.689885
...,...,...,...,...,...,...,...,...,...,...,...
80302,9/9/2012 20:00,wilson,nc,us,light,10800,3 hours,Bright orb being chased by a jet along with se...,9/24/2012,35.721111,-77.915833
80303,9/9/2012 20:10,elmont,ny,us,circle,600,10 minutes,Orange lights seen in Elmont&#44 Long Island&#...,9/24/2012,40.700833,-73.713333
80304,9/9/2012 20:30,mt. juliet,tn,us,light,120,2 minutes,Bright white light moving slowly across sky wi...,9/24/2012,36.200000,-86.518611
80305,9/9/2012 20:30,ventura,ca,us,chevron,900,15 minutes,Beautiful bright blue delta shaped aerobatics.,9/24/2012,34.278333,-119.292222
80306,9/9/2012 20:52,south jordan,ut,us,circle,10,10 seconds,Circular disk with blinking lights scares two ...,9/24/2012,40.562222,-111.928889
80307,9/9/2012 21:00,elkhart,in,us,oval,600,10 minutes,It was the night of sept 9 between 9 and 10 pm...,9/24/2012,41.681944,-85.976667
80308,9/9/2012 21:00,new york city (brooklyn),ny,us,light,1290,21:30,Glowing&#44 circular lights visible in the clo...,9/24/2012,40.714167,-74.006389
80309,9/9/2012 21:00,pawleys island,sc,us,oval,60,less than a minute,One large bright orange flanked by three small...,9/24/2012,33.433056,-79.121667
80310,9/9/2012 21:00,ventura,ca,us,circle,300,5 minutes,Bright Blue Object seen floating in sky near C...,9/24/2012,34.278333,-119.292222
80311,9/9/2012 21:55,charleston,sc,us,flash,900,15 minutes,Orb of light flashing reds and blues&#44 stati...,9/24/2012,32.776389,-79.931111
80312,9/9/2012 23:00,gainesville,ga,us,light,5,5 seconds,Ball of light,9/24/2012,34.297778,-83.824167
80313,9/9/2013 00:15,norfolk,va,us,unknown,1,split second,Two or three lights shoot across sky over nava...,9/30/2013,36.846667,-76.285556
80314,9/9/2013 01:50,buffalo (west of; on highway 90 west),ny,us,triangle,180,3 minutes,Massive Flat Black triangle with 3 red lights.,9/30/2013,42.886389,-78.878611
80315,9/9/2013 03:00,struthers,oh,us,unknown,120,2 minutes,I saw a routaing line of stares that seemed to...,9/9/2013,41.052500,-80.608056
80316,9/9/2013 09:51,san diego,ca,us,light,4,~4 seconds,2 white lights zig-zag over Qualcomm Stadium (...,9/30/2013,32.715278,-117.156389
80317,9/9/2013 12:34,cedar park,tx,us,cigar,8,5-8 seconds,Cigar Shaped Object Descending in the Directio...,9/9/2013,30.505000,-97.820000
80318,9/9/2013 13:10,calmar (canada),ab,ca,unknown,90,45-90 seconds,Fastest dot I have ever seen in the sky&#33,9/9/2013,53.250000,-113.783333
80319,9/9/2013 20:15,clifton,nj,NaN,other,3600,~1hr+,Luminous line seen in New Jersey sky.,9/30/2013,40.858433,-74.163755
80320,9/9/2013 20:20,tuscaloosa,al,us,fireball,60,1:00,White/green object much larger than &quot;shoo...,9/30/2013,33.209722,-87.569167
80321,9/9/2013 20:21,clarksville,tn,us,fireball,3,3 seconds,Green fireball like object shooting across the...,9/30/2013,36.529722,-87.359444
80322,9/9/2013 21:00,aleksandrow (poland),NaN,NaN,light,15,15 seconds,Two points of light following one another in a...,9/30/2013,50.465843,22.891814
80323,9/9/2013 21:00,gainesville,fl,us,triangle,60,1 minute,Three lights in the sky that didn&#39t look li...,9/30/2013,29.651389,-82.325000
80324,9/9/2013 21:00,hamstead (hollyridge),nc,NaN,light,120,2 minutes,8 to ten lights bright orange in color large t...,9/30/2013,34.367594,-77.710548
80325,9/9/2013 21:00,milton (canada),on,ca,fireball,180,3 minutes,Massive Bright Orange Fireball in Sky,9/30/2013,46.300000,-63.216667
80326,9/9/2013 21:00,woodstock,ga,us,sphere,20,20 seconds,Driving 575 at 21:00 hrs saw a white and green...,9/30/2013,34.101389,-84.519444
80327,9/9/2013 21:15,nashville,tn,us,light,600,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.165833,-86.784444
80328,9/9/2013 22:00,boise,id,us,circle,1200,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.613611,-116.202500
80329,9/9/2013 22:00,napa,ca,us,other,1200,hour,Napa UFO&#44,9/30/2013,38.297222,-122.284444
80330,9/9/2013 22:20,vienna,va,us,circle,5,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.901111,-77.265556
80331,9/9/2013 23:00,edmond,ok,us,cigar,1020,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.652778,-97.477778

In [16]:
ufos['latitude'] = ufos['latitude'].replace('33q.200088', '33.200088')

In [39]:
ufos['latitude'] = ufos['latitude'] .astype( 'float64')

In [40]:
ufos.dtypes

datetime               object
city                   object
state                  object
country                object
shape                  object
duration_seconds       object
duration_hours_min     object
comments               object
date_posted            object
latitude              float64
longitude             float64
dtype: object

# Datetime

In [41]:
ufos.astype({'datetime': 'datetime64[ns]'})

,datetime,city,state,country,shape,duration_seconds,duration_hours_min,comments,date_posted,latitude,longitude
0,1949-10-10 20:30:00,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111
1,1949-10-10 21:00:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.384210,-98.581082
2,1955-10-10 17:00:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.200000,-2.916667
3,1956-10-10 21:00:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833
4,1960-10-10 20:00:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611
5,1961-10-10 19:00:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595000,-82.188889
6,1965-10-10 21:00:00,penarth (uk/wales),NaN,gb,circle,180,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2/14/2006,51.434722,-3.180000
7,1965-10-10 23:45:00,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.117500,-73.408333
8,1966-10-10 20:00:00,pell city,al,us,disk,180,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.586111,-86.286111
9,1966-10-10 21:00:00,live oak,fl,us,disk,120,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.294722,-82.984167
10,1968-10-10 13:00:00,hawthorne,ca,us,circle,300,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...,10/31/2003,33.916389,-118.351667
11,1968-10-10 19:00:00,brevard,nc,us,fireball,180,3 minutes,silent red /orange mass of energy floated by t...,6/12/2008,35.233333,-82.734444
12,1970-10-10 16:00:00,bellmore,ny,us,disk,1800,30 min.,silver disc seen by family and neighbors,5/11/2000,40.668611,-73.527500
13,1970-10-10 19:00:00,manchester,ky,us,unknown,180,3 minutes,Slow moving&#44 silent craft accelerated at an...,2/14/2008,37.153611,-83.761944
14,1971-10-10 21:00:00,lexington,nc,us,oval,30,30 seconds,green oval shaped light over my local church&#...,2/14/2010,35.823889,-80.253611
15,1972-10-10 19:00:00,harlan county,ky,us,circle,1200,20minutes,On october 10&#44 1972 myself&#44my 5yrs.daugh...,9/15/2005,36.843056,-83.321944
16,1972-10-10 22:30:00,west bloomfield,mi,us,disk,120,2 minutes,The UFO was so close&#44 my battery in the car...,8/14/2007,42.537778,-83.233056
17,1973-10-10 19:00:00,niantic,ct,us,disk,1800,20-30 min,Oh&#44 what a night &#33 Two (2) saucer-shape...,9/24/2003,41.325278,-72.193611
18,1973-10-10 23:00:00,bermuda nas,NaN,NaN,light,20,20 sec.,saw fast moving blip on the radar scope thin w...,1/11/2002,32.364167,-64.678611
19,1974-10-10 19:30:00,hudson,ma,us,other,2700,45 minutes,Not sure of the eact month or year of this sig...,8/10/1999,42.391667,-71.566667
20,1974-10-10 21:30:00,cardiff (uk/wales),NaN,gb,disk,1200,20 minutes,back in 1974 I was 19 at the time and lived i...,2/1/2007,51.500000,-3.200000
21,1974-10-10 23:00:00,hudson,ks,us,light,1200,one hour?,The light chased us.,7/25/2004,38.105556,-98.659722
22,1975-10-10 17:00:00,north charleston,sc,us,light,360,5-6 minutes,Several Flashing UFO lights over Charleston Na...,2/14/2008,32.854444,-79.975000
23,1976-10-10 20:30:00,washougal,wa,us,oval,60,1 minute,Three extremely large lights hanging above nea...,2/7/2014,45.582778,-122.352222
24,1976-10-10 22:00:00,stoke mandeville (uk/england),NaN,gb,cigar,3,3 seconds,White object over Buckinghamshire UK.,12/12/2009,51.783333,-0.783333
25,1977-10-10 12:00:00,san antonio,tx,us,other,30,30 seconds,i was about six or seven and my family and me ...,2/24/2005,29.423889,-98.493333
26,1977-10-10 22:00:00,louisville,ky,us,light,30,approx: 30 seconds,HBCCUFO CANADIAN REPORT: Pilot Sighting Of Un...,3/17/2004,38.254167,-85.759444
27,1978-10-10 02:00:00,elmont,ny,us,rectangle,300,5min,A memory I will never forget that happened men...,2/1/2007,40.700833,-73.713333
28,1979-10-10 00:00:00,poughkeepsie,ny,us,chevron,900,15 minutes,1/4 moon-like&#44 its &#39chord&#39 or flat s...,4/16/2005,41.700278,-73.921389
29,1979-10-10 22:00:00,saddle lake (canada),ab,NaN,triangle,270,4.5 or more min.,Lights far above&#44 that glance; then flee f...,1/19/2005,53.970571,-111.689885
...,...,...,...,...,...,...,...,...,...,...,...
80302,2012-09-09 20:00:00,wilson,nc,us,light,10800,3 hours,Bright orb being chased by a jet along with se...,9/24/2012,35.721111,-77.915833
80303,2012-09-09 20:10:00,elmont,ny,us,circle,600,10 minutes,Orange lights seen in Elmont&#44 Long Island&#...,9/24/2012,40.700833,-73.713333
80304,2012-09-09 20:30:00,mt. juliet,tn,us,light,120,2 minutes,Bright white light moving slowly across sky wi...,9/24/2012,36.200000,-86.518611
80305,2012-09-09 20:30:00,ventura,ca,us,chevron,900,15 minutes,Beautiful bright blue delta shaped aerobatics.,9/24/2012,34.278333,-119.292222
80306,2012-09-09 20:52:00,south jordan,ut,us,circle,10,10 seconds,Circular disk with blinking lights scares two ...,9/24/2012,40.562222,-111.928889
80307,2012-09-09 21:00:00,elkhart,in,us,oval,600,10 minutes,It was the night of sept 9 between 9 and 10 pm...,9/24/2012,41.681944,-85.976667
80308,2012-09-09 21:00:00,new york city (brooklyn),ny,us,light,1290,21:30,Glowing&#44 circular lights visible in the clo...,9/24/2012,40.714167,-74.006389
80309,2012-09-09 21:00:00,pawleys island,sc,us,oval,60,less than a minute,One large bright orange flanked by three small...,9/24/2012,33.433056,-79.121667
80310,2012-09-09 21:00:00,ventura,ca,us,circle,300,5 minutes,Bright Blue Object seen floating in sky near C...,9/24/2012,34.278333,-119.292222
80311,2012-09-09 21:55:00,charleston,sc,us,flash,900,15 minutes,Orb of light flashing reds and blues&#44 stati...,9/24/2012,32.776389,-79.931111
80312,2012-09-09 23:00:00,gainesville,ga,us,light,5,5 seconds,Ball of light,9/24/2012,34.297778,-83.824167
80313,2013-09-09 00:15:00,norfolk,va,us,unknown,1,split second,Two or three lights shoot across sky over nava...,9/30/2013,36.846667,-76.285556
80314,2013-09-09 01:50:00,buffalo (west of; on highway 90 west),ny,us,triangle,180,3 minutes,Massive Flat Black triangle with 3 red lights.,9/30/2013,42.886389,-78.878611
80315,2013-09-09 03:00:00,struthers,oh,us,unknown,120,2 minutes,I saw a routaing line of stares that seemed to...,9/9/2013,41.052500,-80.608056
80316,2013-09-09 09:51:00,san diego,ca,us,light,4,~4 seconds,2 white lights zig-zag over Qualcomm Stadium (...,9/30/2013,32.715278,-117.156389
80317,2013-09-09 12:34:00,cedar park,tx,us,cigar,8,5-8 seconds,Cigar Shaped Object Descending in the Directio...,9/9/2013,30.505000,-97.820000
80318,2013-09-09 13:10:00,calmar (canada),ab,ca,unknown,90,45-90 seconds,Fastest dot I have ever seen in the sky&#33,9/9/2013,53.250000,-113.783333
80319,2013-09-09 20:15:00,clifton,nj,NaN,other,3600,~1hr+,Luminous line seen in New Jersey sky.,9/30/2013,40.858433,-74.163755
80320,2013-09-09 20:20:00,tuscaloosa,al,us,fireball,60,1:00,White/green object much larger than &quot;shoo...,9/30/2013,33.209722,-87.569167
80321,2013-09-09 20:21:00,clarksville,tn,us,fireball,3,3 seconds,Green fireball like object shooting across the...,9/30/2013,36.529722,-87.359444
80322,2013-09-09 21:00:00,aleksandrow (poland),NaN,NaN,light,15,15 seconds,Two points of light following one another in a...,9/30/2013,50.465843,22.891814
80323,2013-09-09 21:00:00,gainesville,fl,us,triangle,60,1 minute,Three lights in the sky that didn&#39t look li...,9/30/2013,29.651389,-82.325000
80324,2013-09-09 21:00:00,hamstead (hollyridge),nc,NaN,light,120,2 minutes,8 to ten lights bright orange in color large t...,9/30/2013,34.367594,-77.710548
80325,2013-09-09 21:00:00,milton (canada),on,ca,fireball,180,3 minutes,Massive Bright Orange Fireball in Sky,9/30/2013,46.300000,-63.216667
80326,2013-09-09 21:00:00,woodstock,ga,us,sphere,20,20 seconds,Driving 575 at 21:00 hrs saw a white and green...,9/30/2013,34.101389,-84.519444
80327,2013-09-09 21:15:00,nashville,tn,us,light,600,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.165833,-86.784444
80328,2013-09-09 22:00:00,boise,id,us,circle,1200,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.613611,-116.202500
80329,2013-09-09 22:00:00,napa,ca,us,other,1200,hour,Napa UFO&#44,9/30/2013,38.297222,-122.284444
80330,2013-09-09 22:20:00,vienna,va,us,circle,5,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.901111,-77.265556
80331,2013-09-09 23:00:00,edmond,ok,us,cigar,1020,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.652778,-97.477778

In [42]:
ufos.dtypes

datetime               object
city                   object
state                  object
country                object
shape                  object
duration_seconds       object
duration_hours_min     object
comments               object
date_posted            object
latitude              float64
longitude             float64
dtype: object

In [43]:
ufos['24' in ufos['datetime']]

KeyError: False

In [44]:
ufos['date_24'] = ufos['datetime'].apply(lambda x: '24:' in x)

In [45]:
ufos[ufos['date_24'] == True ]

Empty DataFrame
Columns: [datetime, city, state, country, shape, duration_seconds, duration_hours_min, comments, date_posted, latitude, longitude, date_24]
Index: []

In [46]:
ufos['datetime'] = ufos['datetime'].replace('24:', '00:')

In [47]:
ufos.astype({'datetime': 'datetime64[ns]'}, inplace = True)

,datetime,city,state,country,shape,duration_seconds,duration_hours_min,comments,date_posted,latitude,longitude,date_24
0,1949-10-10 20:30:00,san marcos,tx,us,cylinder,2700,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111,False
1,1949-10-10 21:00:00,lackland afb,tx,NaN,light,7200,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.384210,-98.581082,False
2,1955-10-10 17:00:00,chester (uk/england),NaN,gb,circle,20,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.200000,-2.916667,False
3,1956-10-10 21:00:00,edna,tx,us,circle,20,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833,False
4,1960-10-10 20:00:00,kaneohe,hi,us,light,900,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611,False
5,1961-10-10 19:00:00,bristol,tn,us,sphere,300,5 minutes,My father is now 89 my brother 52 the girl wit...,4/27/2007,36.595000,-82.188889,False
6,1965-10-10 21:00:00,penarth (uk/wales),NaN,gb,circle,180,about 3 mins,penarth uk circle 3mins stayed 30ft above m...,2/14/2006,51.434722,-3.180000,False
7,1965-10-10 23:45:00,norwalk,ct,us,disk,1200,20 minutes,A bright orange color changing to reddish colo...,10/2/1999,41.117500,-73.408333,False
8,1966-10-10 20:00:00,pell city,al,us,disk,180,3 minutes,Strobe Lighted disk shape object observed clos...,3/19/2009,33.586111,-86.286111,False
9,1966-10-10 21:00:00,live oak,fl,us,disk,120,several minutes,Saucer zaps energy from powerline as my pregna...,5/11/2005,30.294722,-82.984167,False
10,1968-10-10 13:00:00,hawthorne,ca,us,circle,300,5 min.,ROUND &#44 ORANGE &#44 WITH WHAT I WOULD SAY W...,10/31/2003,33.916389,-118.351667,False
11,1968-10-10 19:00:00,brevard,nc,us,fireball,180,3 minutes,silent red /orange mass of energy floated by t...,6/12/2008,35.233333,-82.734444,False
12,1970-10-10 16:00:00,bellmore,ny,us,disk,1800,30 min.,silver disc seen by family and neighbors,5/11/2000,40.668611,-73.527500,False
13,1970-10-10 19:00:00,manchester,ky,us,unknown,180,3 minutes,Slow moving&#44 silent craft accelerated at an...,2/14/2008,37.153611,-83.761944,False
14,1971-10-10 21:00:00,lexington,nc,us,oval,30,30 seconds,green oval shaped light over my local church&#...,2/14/2010,35.823889,-80.253611,False
15,1972-10-10 19:00:00,harlan county,ky,us,circle,1200,20minutes,On october 10&#44 1972 myself&#44my 5yrs.daugh...,9/15/2005,36.843056,-83.321944,False
16,1972-10-10 22:30:00,west bloomfield,mi,us,disk,120,2 minutes,The UFO was so close&#44 my battery in the car...,8/14/2007,42.537778,-83.233056,False
17,1973-10-10 19:00:00,niantic,ct,us,disk,1800,20-30 min,Oh&#44 what a night &#33 Two (2) saucer-shape...,9/24/2003,41.325278,-72.193611,False
18,1973-10-10 23:00:00,bermuda nas,NaN,NaN,light,20,20 sec.,saw fast moving blip on the radar scope thin w...,1/11/2002,32.364167,-64.678611,False
19,1974-10-10 19:30:00,hudson,ma,us,other,2700,45 minutes,Not sure of the eact month or year of this sig...,8/10/1999,42.391667,-71.566667,False
20,1974-10-10 21:30:00,cardiff (uk/wales),NaN,gb,disk,1200,20 minutes,back in 1974 I was 19 at the time and lived i...,2/1/2007,51.500000,-3.200000,False
21,1974-10-10 23:00:00,hudson,ks,us,light,1200,one hour?,The light chased us.,7/25/2004,38.105556,-98.659722,False
22,1975-10-10 17:00:00,north charleston,sc,us,light,360,5-6 minutes,Several Flashing UFO lights over Charleston Na...,2/14/2008,32.854444,-79.975000,False
23,1976-10-10 20:30:00,washougal,wa,us,oval,60,1 minute,Three extremely large lights hanging above nea...,2/7/2014,45.582778,-122.352222,False
24,1976-10-10 22:00:00,stoke mandeville (uk/england),NaN,gb,cigar,3,3 seconds,White object over Buckinghamshire UK.,12/12/2009,51.783333,-0.783333,False
25,1977-10-10 12:00:00,san antonio,tx,us,other,30,30 seconds,i was about six or seven and my family and me ...,2/24/2005,29.423889,-98.493333,False
26,1977-10-10 22:00:00,louisville,ky,us,light,30,approx: 30 seconds,HBCCUFO CANADIAN REPORT: Pilot Sighting Of Un...,3/17/2004,38.254167,-85.759444,False
27,1978-10-10 02:00:00,elmont,ny,us,rectangle,300,5min,A memory I will never forget that happened men...,2/1/2007,40.700833,-73.713333,False
28,1979-10-10 00:00:00,poughkeepsie,ny,us,chevron,900,15 minutes,1/4 moon-like&#44 its &#39chord&#39 or flat s...,4/16/2005,41.700278,-73.921389,False
29,1979-10-10 22:00:00,saddle lake (canada),ab,NaN,triangle,270,4.5 or more min.,Lights far above&#44 that glance; then flee f...,1/19/2005,53.970571,-111.689885,False
...,...,...,...,...,...,...,...,...,...,...,...,...
80302,2012-09-09 20:00:00,wilson,nc,us,light,10800,3 hours,Bright orb being chased by a jet along with se...,9/24/2012,35.721111,-77.915833,False
80303,2012-09-09 20:10:00,elmont,ny,us,circle,600,10 minutes,Orange lights seen in Elmont&#44 Long Island&#...,9/24/2012,40.700833,-73.713333,False
80304,2012-09-09 20:30:00,mt. juliet,tn,us,light,120,2 minutes,Bright white light moving slowly across sky wi...,9/24/2012,36.200000,-86.518611,False
80305,2012-09-09 20:30:00,ventura,ca,us,chevron,900,15 minutes,Beautiful bright blue delta shaped aerobatics.,9/24/2012,34.278333,-119.292222,False
80306,2012-09-09 20:52:00,south jordan,ut,us,circle,10,10 seconds,Circular disk with blinking lights scares two ...,9/24/2012,40.562222,-111.928889,False
80307,2012-09-09 21:00:00,elkhart,in,us,oval,600,10 minutes,It was the night of sept 9 between 9 and 10 pm...,9/24/2012,41.681944,-85.976667,False
80308,2012-09-09 21:00:00,new york city (brooklyn),ny,us,light,1290,21:30,Glowing&#44 circular lights visible in the clo...,9/24/2012,40.714167,-74.006389,False
80309,2012-09-09 21:00:00,pawleys island,sc,us,oval,60,less than a minute,One large bright orange flanked by three small...,9/24/2012,33.433056,-79.121667,False
80310,2012-09-09 21:00:00,ventura,ca,us,circle,300,5 minutes,Bright Blue Object seen floating in sky near C...,9/24/2012,34.278333,-119.292222,False
80311,2012-09-09 21:55:00,charleston,sc,us,flash,900,15 minutes,Orb of light flashing reds and blues&#44 stati...,9/24/2012,32.776389,-79.931111,False
80312,2012-09-09 23:00:00,gainesville,ga,us,light,5,5 seconds,Ball of light,9/24/2012,34.297778,-83.824167,False
80313,2013-09-09 00:15:00,norfolk,va,us,unknown,1,split second,Two or three lights shoot across sky over nava...,9/30/2013,36.846667,-76.285556,False
80314,2013-09-09 01:50:00,buffalo (west of; on highway 90 west),ny,us,triangle,180,3 minutes,Massive Flat Black triangle with 3 red lights.,9/30/2013,42.886389,-78.878611,False
80315,2013-09-09 03:00:00,struthers,oh,us,unknown,120,2 minutes,I saw a routaing line of stares that seemed to...,9/9/2013,41.052500,-80.608056,False
80316,2013-09-09 09:51:00,san diego,ca,us,light,4,~4 seconds,2 white lights zig-zag over Qualcomm Stadium (...,9/30/2013,32.715278,-117.156389,False
80317,2013-09-09 12:34:00,cedar park,tx,us,cigar,8,5-8 seconds,Cigar Shaped Object Descending in the Directio...,9/9/2013,30.505000,-97.820000,False
80318,2013-09-09 13:10:00,calmar (canada),ab,ca,unknown,90,45-90 seconds,Fastest dot I have ever seen in the sky&#33,9/9/2013,53.250000,-113.783333,False
80319,2013-09-09 20:15:00,clifton,nj,NaN,other,3600,~1hr+,Luminous line seen in New Jersey sky.,9/30/2013,40.858433,-74.163755,False
80320,2013-09-09 20:20:00,tuscaloosa,al,us,fireball,60,1:00,White/green object much larger than &quot;shoo...,9/30/2013,33.209722,-87.569167,False
80321,2013-09-09 20:21:00,clarksville,tn,us,fireball,3,3 seconds,Green fireball like object shooting across the...,9/30/2013,36.529722,-87.359444,False
80322,2013-09-09 21:00:00,aleksandrow (poland),NaN,NaN,light,15,15 seconds,Two points of light following one another in a...,9/30/2013,50.465843,22.891814,False
80323,2013-09-09 21:00:00,gainesville,fl,us,triangle,60,1 minute,Three lights in the sky that didn&#39t look li...,9/30/2013,29.651389,-82.325000,False
80324,2013-09-09 21:00:00,hamstead (hollyridge),nc,NaN,light,120,2 minutes,8 to ten lights bright orange in color large t...,9/30/2013,34.367594,-77.710548,False
80325,2013-09-09 21:00:00,milton (canada),on,ca,fireball,180,3 minutes,Massive Bright Orange Fireball in Sky,9/30/2013,46.300000,-63.216667,False
80326,2013-09-09 21:00:00,woodstock,ga,us,sphere,20,20 seconds,Driving 575 at 21:00 hrs saw a white and green...,9/30/2013,34.101389,-84.519444,False
80327,2013-09-09 21:15:00,nashville,tn,us,light,600,10 minutes,Round from the distance/slowly changing colors...,9/30/2013,36.165833,-86.784444,False
80328,2013-09-09 22:00:00,boise,id,us,circle,1200,20 minutes,Boise&#44 ID&#44 spherical&#44 20 min&#44 10 r...,9/30/2013,43.613611,-116.202500,False
80329,2013-09-09 22:00:00,napa,ca,us,other,1200,hour,Napa UFO&#44,9/30/2013,38.297222,-122.284444,False
80330,2013-09-09 22:20:00,vienna,va,us,circle,5,5 seconds,Saw a five gold lit cicular craft moving fastl...,9/30/2013,38.901111,-77.265556,False
80331,2013-09-09 23:00:00,edmond,ok,us,cigar,1020,17 minutes,2 witnesses 2 miles apart&#44 Red &amp; White...,9/30/2013,35.652778,-97.477778,False

In [48]:
ufos['date_24'] = ufos['datetime'].apply(lambda x: '24:' in x)
ufos[ufos['date_24'] == True ]

Empty DataFrame
Columns: [datetime, city, state, country, shape, duration_seconds, duration_hours_min, comments, date_posted, latitude, longitude, date_24]
Index: []

In [49]:
ufos['datetime'] = ufos['datetime'].replace('24:', '00:')

In [50]:
ufos[ufos['date_24'] == True ]

Empty DataFrame
Columns: [datetime, city, state, country, shape, duration_seconds, duration_hours_min, comments, date_posted, latitude, longitude, date_24]
Index: []

In [51]:
ufos['datetime'] = ufos['datetime'].apply(lambda x: x.replace('24:', '00:'))

In [56]:
ufos['datetime'] = ufos['datetime'].astype('datetime64[ns]')

# Duration_seconds

In [27]:
ufos.astype({'duration_seconds': float})

ValueError: could not convert string to float: '2`'

In [61]:
ufos['duration_seconds'] = ufos['duration_seconds'].apply(lambda x: x.replace('`', ''))

In [62]:
ufos['duration_seconds'] = ufos['duration_seconds'].astype('float64')

In [66]:
ufos.dtypes

datetime              datetime64[ns]
city                          object
state                         object
country                       object
shape                         object
duration_seconds             float64
duration_hours_min            object
comments                      object
date_posted           datetime64[ns]
latitude                     float64
longitude                    float64
date_24                         bool
dtype: object

In [64]:
ufos.head()

,datetime,city,state,country,shape,duration_seconds,duration_hours_min,comments,date_posted,latitude,longitude,date_24
0,1949-10-10 20:30:00,san marcos,tx,us,cylinder,2700.0,45 minutes,This event took place in early fall around 194...,4/27/2004,29.883056,-97.941111,False
1,1949-10-10 21:00:00,lackland afb,tx,NaN,light,7200.0,1-2 hrs,1949 Lackland AFB&#44 TX. Lights racing acros...,12/16/2005,29.384210,-98.581082,False
2,1955-10-10 17:00:00,chester (uk/england),NaN,gb,circle,20.0,20 seconds,Green/Orange circular disc over Chester&#44 En...,1/21/2008,53.200000,-2.916667,False
3,1956-10-10 21:00:00,edna,tx,us,circle,20.0,1/2 hour,My older brother and twin sister were leaving ...,1/17/2004,28.978333,-96.645833,False
4,1960-10-10 20:00:00,kaneohe,hi,us,light,900.0,15 minutes,AS a Marine 1st Lt. flying an FJ4B fighter/att...,1/22/2004,21.418056,-157.803611,False

# NaN values

In [67]:
ufos.isnull()

,datetime,city,state,country,shape,duration_seconds,duration_hours_min,comments,date_posted,latitude,longitude,date_24
0,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False
6,False,False,True,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False,False,False
18,False,False,True,True,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,False,False
20,False,False,True,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,False,False
24,False,False,True,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,False,False
29,False,False,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
80302,False,False,False,False,False,False,False,False,False,False,False,False
80303,False,False,False,False,False,False,False,False,False,False,False,False
80304,False,False,False,False,False,False,False,False,False,False,False,False
80305,False,False,False,False,False,False,False,False,False,False,False,False
80306,False,False,False,False,False,False,False,False,False,False,False,False
80307,False,False,False,False,False,False,False,False,False,False,False,False
80308,False,False,False,False,False,False,False,False,False,False,False,False
80309,False,False,False,False,False,False,False,False,False,False,False,False
80310,False,False,False,False,False,False,False,False,False,False,False,False
80311,False,False,False,False,False,False,False,False,False,False,False,False
80312,False,False,False,False,False,False,False,False,False,False,False,False
80313,False,False,False,False,False,False,False,False,False,False,False,False
80314,False,False,False,False,False,False,False,False,False,False,False,False
80315,False,False,False,False,False,False,False,False,False,False,False,False
80316,False,False,False,False,False,False,False,False,False,False,False,False
80317,False,False,False,False,False,False,False,False,False,False,False,False
80318,False,False,False,False,False,False,False,False,False,False,False,False
80319,False,False,False,True,False,False,False,False,False,False,False,False
80320,False,False,False,False,False,False,False,False,False,False,False,False
80321,False,False,False,False,False,False,False,False,False,False,False,False
80322,False,False,True,True,False,False,False,False,False,False,False,False
80323,False,False,False,False,False,False,False,False,False,False,False,False
80324,False,False,False,True,False,False,False,False,False,False,False,False
80325,False,False,False,False,False,False,False,False,False,False,False,False
80326,False,False,False,False,False,False,False,False,False,False,False,False
80327,False,False,False,False,False,False,False,False,False,False,False,False
80328,False,False,False,False,False,False,False,False,False,False,False,False
80329,False,False,False,False,False,False,False,False,False,False,False,False
80330,False,False,False,False,False,False,False,False,False,False,False,False
80331,False,False,False,False,False,False,False,False,False,False,False,False

In [68]:
ufos.isnull().sum()

datetime                 0
city                     0
state                 5797
country               9670
shape                 1932
duration_seconds         0
duration_hours_min       0
comments                15
date_posted              0
latitude                 0
longitude                0
date_24                  0
dtype: int64

In [69]:
ufos['comments'] = ufos['comments'].fillna('No comments')

In [70]:
ufos.isnull().sum()

datetime                 0
city                     0
state                 5797
country               9670
shape                 1932
duration_seconds         0
duration_hours_min       0
comments                 0
date_posted              0
latitude                 0
longitude                0
date_24                  0
dtype: int64