In [1]:
google_api = "https://www.googleapis.com/customsearch/v1?"

In [2]:
params = {
    "key": "AIzaSyDeDEXWk7bq0r0GYzz-Pmc6dWqRGVxJ2Zc",
    "cx": "003240156206868727193:scrr7eqktoy",
    "fields": "kind,items(title,link,snippet),queries(request(title,totalResults,count,startIndex))",
    "q": "madrid",
    "start": 1
}

In [3]:
import requests
import json

In [4]:
response = requests.get(google_api, params=params)

In [5]:
response

In [6]:
print(json.dumps(response.json(), sort_keys=True, indent=4))

{
    "items": [
        {
            "link": "https://summit.ironhack.com/",
            "snippet": "Enjoy a guided tour and discover some of the most popular places in Madrid. You\n'll also grab some beers in the city center. This is an optional activity, but you\u00a0...",
            "title": "Ironhack Alumni Summit"
        },
        {
            "link": "http://blog.ironhack.com/madrid-2/",
            "snippet": "Jan 18, 2019 ... Our alumni Elise tells you all about her background, why she joined Ironhack, \nand her experience of the web dev bootcamp. read more\u00a0...",
            "title": "Madrid | Ironhack Blog"
        },
        {
            "link": "https://www.ironhack.com/fr/campus/madrid",
            "snippet": "Formez vous sur Madrid en D\u00e9veloppement Web ou en UX/UI design gr\u00e2ce \u00e0 \nnos bootcamps \u00e0 temps plein ou temps partiel.",
            "title": "Ironhack Madrid - Bootcamps en D\u00e9veloppement Web et UX/UI ..."
        },
        {
            "link": "https://www.ironhack.com/",
            "snippet": "Learn to code and UX/UI design through one of our full time or part time courses. \nWeb Development Bootcamp and UX/UI Design Bootcamp in Madrid,\u00a0...",
            "title": "Ironhack Web Development Bootcamp & UX/UI Design Bootcamp"
        },
        {
            "link": "https://blog.ironhack.com/category/madrid-en/",
            "snippet": "Dec 3, 2018 ... Our latest articles Inside Cabify \u2013 Our alumni experience by Alberto Marcos | Aug \n1, 2016 | Alumni, Madrid At Ironhack, we like to interview\u00a0...",
            "title": "Madrid Archives - Ironhack Blog"
        },
        {
            "link": "https://blog.ironhack.com/es/campus-de-madrid/page/5/",
            "snippet": "In May this year, I was at a point in my life that many of you will identify with. I had \nbeen studying for the last 8 years of my life, architecture degree for 7 of them\u2026",
            "title": "Campus de Madrid - Ironhack Blog"
        },
        {
            "link": "https://blog.ironhack.com/es/campus-de-madrid/page/12/",
            "snippet": "First impressions count, and the window in which they're formed is usually small. \nThis is why we're mindful of every minute, from the moment the students walk\u00a0...",
            "title": "Campus de Madrid - Ironhack Blog"
        },
        {
            "link": "https://blog.ironhack.com/es/campus-de-madrid/page/10/",
            "snippet": "Jimmy: Alright, so we are recording. Welcome back to another Ironhack Student \nPodcast, I am Jimmy. And in case you don't know what Ironhack is we are a\u00a0...",
            "title": "Campus de Madrid - Ironhack Blog"
        },
        {
            "link": "https://blog.ironhack.com/es/madrid-2-2/page/8/",
            "snippet": "Since 2013 Ironhack has been helping people answer the \"is a coding bootcamp \nfor me\" question. We've helped people change careers into the field of their\u00a0...",
            "title": "Madrid (ES) | Ironhack Blog"
        },
        {
            "link": "https://blog.ironhack.com/es/campus-de-madrid/page/3/",
            "snippet": "Since the dawn of days, humans have gathered together to socialize and share, \nan exercise as old as time that has given us advantage over other animals. And\u00a0...",
            "title": "Campus de Madrid - Ironhack Blog"
        }
    ],
    "kind": "customsearch#search",
    "queries": {
        "request": [
            {
                "count": 10,
                "startIndex": 1,
                "title": "Google Custom Search - madrid",
                "totalResults": "1800"
            }
        ]
    }
}

In [7]:
import pandas as pd

In [8]:
events = pd.DataFrame(response.json())

ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.

In [ ]:
data = response.json()

In [ ]:
data['items']

In [ ]:
json_normalize(data, 'items', [ 'link', 'snippet', 'title'], errors='ignore')

In [9]:
events = pd.DataFrame(data['items'])

NameError: name 'data' is not defined

In [10]:
events

NameError: name 'events' is not defined

In [11]:
events.groupby(['snippet']).count()

NameError: name 'events' is not defined

In [12]:
events.shape

NameError: name 'events' is not defined

In [13]:
events

NameError: name 'events' is not defined

In [14]:
params_miami = {
    "key": "AIzaSyDeDEXWk7bq0r0GYzz-Pmc6dWqRGVxJ2Zc",
    "cx": "003240156206868727193:scrr7eqktoy",
    "fields": "kind,items(title,link,snippet),queries(request(title,totalResults,count,startIndex))",
    "q": "miami",
    "start": 1
}

In [15]:
data_miami = requests.get(google_api, params=params_miami).json()

In [16]:
data_miami

{'kind': 'customsearch#search',
 'queries': {'request': [{'title': 'Google Custom Search - miami',
    'totalResults': '1610',
    'count': 10,
    'startIndex': 1}]},
 'items': [{'title': 'Ironhack Web Development Bootcamp & UX/UI Design Bootcamp',
   'link': 'https://www.ironhack.com/',
   'snippet': '... of our full time or part time courses. Web Development Bootcamp and UX/UI \nDesign Bootcamp in Madrid, Barcelona, Miami, Paris, Mexico City, Berlin, Bogotá\n,\xa0...'},
  {'title': 'Ironhack - Bootcamps and Courses in Web Coding and UX/UI Design',
   'link': 'https://www.ironhack.com/en/web-barcelona-14',
   'snippet': '990 Biscayne Blvd. Ste 503 - Miami FL 33132 © 2013-2018 Ironhack. All Rights \nReserved. Switchup Logo CourseReport Logo Licensed by: Florida Department\xa0...'},
  {'title': 'Miami (EN) | Ironhack Blog',
   'link': 'https://blog.ironhack.com/locations-miami/',
   'snippet': 'He has gone on to work as a developer in the South Florida Tech industry. \nRecently, Ariel placed 2nd at the Miami Bitcoin Hackathon. (Check out his project\n\xa0...'},
  {'title': 'Miami Archives - Ironhack Blog',
   'link': 'https://blog.ironhack.com/category/miami-en/',
   'snippet': 'He has gone on to work as a developer in the South Florida Tech industry. \nRecently, Ariel placed 2nd at the Miami Bitcoin Hackathon. (Check out his project\n\xa0...'},
  {'title': 'Miami (EN) | Ironhack Blog',
   'link': 'https://blog.ironhack.com/locations-miami/page/2/',
   'snippet': 'No Results Found. The page you requested could not be found. Try refining your \nsearch, or use the navigation above to locate the post.'},
  {'title': 'Web Development Bootcamp',
   'link': 'https://code.ironhack.com/web-dev-bootcamp-en-sem-mia/',
   'snippet': 'Career Support. Career Support. 120 SW 8th St. Miami, Fl 33130. +1-954-398-\n5044 EOM. mia@ironhack.com. Full-Time and In-person Coding Bootcamp\xa0...'},
  {'title': 'Curso de Data Analytics en Miami | Bootcamp de 9 Semanas ...',
   'link': 'https://www.ironhack.com/es/cursos/data-analytics-bootcamp',
   'snippet': 'Después de 9 semanas de trabajo intensivo en el curso de análisis de datos, los \nalumnos de Ironhack se gradúan como analistas de datos junior full-stack.'},
  {'title': 'A Virtual Tour of Our Ironhack Miami Campus - Ironhack Blog',
   'link': 'https://blog.ironhack.com/2016/06/27/a-third-of-ironhack-calls-miami-home/',
   'snippet': 'Jun 27, 2016 ... Building.co is a collaborative workspace that accommodates local tech \ncompanies; it also happens to be home to the Ironhack Miami campus.'},
  {'title': 'Curso de UX/UI Design em Miami | Bootcamp de 9 Semanas ...',
   'link': 'https://www.ironhack.com/pt/cursos/ux-ui-design-bootcamp-learn-ux-design',
   'snippet': 'Curso de UX design: em 9 semanas aprendes os fundamentos do UX design, do \nUI design e também como produzir bons designs web/móvel para os teus\xa0...'},
  {'title': 'miami Archives - Ironhack Blog',
   'link': 'https://blog.ironhack.com/tag/miami-en/',
   'snippet': 'He has gone on to work as a developer in the South Florida Tech industry. \nRecently, Ariel placed 2nd at the Miami Bitcoin Hackathon. (Check out his project\n\xa0...'}]}

In [17]:
events_miami = pd.DataFrame(data_miami['items'])

In [18]:
events_miami.sort_values(by='snippet')

,link,snippet,title
0,https://www.ironhack.com/,... of our full time or part time courses. Web...,Ironhack Web Development Bootcamp & UX/UI Desi...
1,https://www.ironhack.com/en/web-barcelona-14,990 Biscayne Blvd. Ste 503 - Miami FL 33132 © ...,Ironhack - Bootcamps and Courses in Web Coding...
5,https://code.ironhack.com/web-dev-bootcamp-en-...,Career Support. Career Support. 120 SW 8th St....,Web Development Bootcamp
8,https://www.ironhack.com/pt/cursos/ux-ui-desig...,Curso de UX design: em 9 semanas aprendes os f...,Curso de UX/UI Design em Miami | Bootcamp de 9...
6,https://www.ironhack.com/es/cursos/data-analyt...,Después de 9 semanas de trabajo intensivo en e...,Curso de Data Analytics en Miami | Bootcamp de...
2,https://blog.ironhack.com/locations-miami/,He has gone on to work as a developer in the S...,Miami (EN) | Ironhack Blog
3,https://blog.ironhack.com/category/miami-en/,He has gone on to work as a developer in the S...,Miami Archives - Ironhack Blog
9,https://blog.ironhack.com/tag/miami-en/,He has gone on to work as a developer in the S...,miami Archives - Ironhack Blog
7,https://blog.ironhack.com/2016/06/27/a-third-o...,"Jun 27, 2016 ... Building.co is a collaborativ...",A Virtual Tour of Our Ironhack Miami Campus - ...
4,https://blog.ironhack.com/locations-miami/page/2/,No Results Found. The page you requested could...,Miami (EN) | Ironhack Blog

In [19]:
events_miami.groupby(['snippet']).count()

                                                    link  title
snippet
... of our full time or part time courses. Web ...     1      1
990 Biscayne Blvd. Ste 503 - Miami FL 33132 © 2...     1      1
Career Support. Career Support. 120 SW 8th St. ...     1      1
Curso de UX design: em 9 semanas aprendes os fu...     1      1
Después de 9 semanas de trabajo intensivo en el...     1      1
He has gone on to work as a developer in the So...     3      3
Jun 27, 2016 ... Building.co is a collaborative...     1      1
No Results Found. The page you requested could ...     1      1

In [20]:
cities = ['Amsterdam', 'Barcelona', 'Berlin', 'Bogotá',  'Lisbon', 'Madrid', 'Mexico City', 'Miami', 'Munich','Paris', 'São Paolo' ]

In [21]:
all_cities_df = pd.DataFrame()
for city in cities:
    print(city)
    params = {
    "key": "AIzaSyDeDEXWk7bq0r0GYzz-Pmc6dWqRGVxJ2Zc",
    "cx": "003240156206868727193:scrr7eqktoy",
    "fields": "kind,items(title,link,snippet),queries(request(title,totalResults,count,startIndex))",
    "q": city.lower(),
    "start": 1
    }
    data = requests.get(google_api, params=params).json()
    dataframe = pd.DataFrame(data['items'])
    dataframe['city'] = city
    print(dataframe[['link']].head(1))
    all_cities_df = all_cities_df.append(dataframe,ignore_index=True)
    print(all_cities_df.head(1))

Amsterdam
                                             link
0  https://code.ironhack.com/iamcoding-amsterdam/
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Barcelona
                                           link
0  https://www.ironhack.com/en/web-barcelona-14
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Berlin
                                          link
0  https://blog.ironhack.com/locations-berlin/
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Bogotá
                                          link
0  https://www.ironhack.com/nl/locaties/bogota
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Lisbon
                                       link
0  https://code.ironhack.com/wecode-lisbon/
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Madrid
                           link
0  https://summit.ironhack.com/
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Mexico City
                               link
0  https://www.ironhack.com/en/team
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Miami
                        link
0  https://www.ironhack.com/
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Munich
                                           link
0  https://www.ironhack.com/en/locations/munich
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
Paris
                                         link
0  https://blog.ironhack.com/locations-paris/
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam
São Paolo
                                             link
0  https://blog.ironhack.com/locations-sao-paolo/
                                             link  \
0  https://code.ironhack.com/iamcoding-amsterdam/

                                             snippet  \
0  For a whole day, you'll immerse yourself in th...

                                        title       city
0  I AM CODING - Ironhack Amsterdam workshops  Amsterdam

In [22]:
all_cities_df.groupby('snippet').count().sort_values(by='link', ascending=False)

                                                    link  title  city
snippet
Amsterdam Barcelona Berlin Bogotá Lisbon Madrid...    10     10    10
... of our full time or part time courses. Web ...     5      5     5
2018 Campus Amsterdam. 2018 Campus São Paulo. 2...     4      4     4
Amsterdam Barcelona Berlin Bogotá Lisbon Madrid...     4      4     4
Amsterdam Barcelona Berlijn Bogotá Lisbon Madri...     4      4     4
In May this year, I was at a point in my life t...     3      3     3
He has gone on to work as a developer in the So...     3      3     3
Join Ironhack. Do you want to study at Ironhack...     2      2     2
Join Ironhack. Do you want to study at Ironhack...     2      2     2
I find myself at a coding school called Ironhac...     2      2     2
Learn to code and UX/UI design through one of o...     2      2     2
Jan 18, 2019 ... Organizer. Ironhack Amsterdam....     2      2     2
Mexico City · Berlin · Amsterdam · São Paulo. L...     2      2     2
No Results Found. The page you requested could ...     2      2     2
Feb 6, 2019 ... Ironhack is a global tech schoo...     2      2     2
Thor completed the Web Development Bootcamp in ...     2      2     2
Ironhack is an international school with course...     2      2     2
Ironhack is a global tech school with campuses ...     2      2     2
... time courses. Web Development Bootcamp and ...     2      2     2
Jan 30, 2019 ... The future of work is digital....     1      1     1
Jan 18, 2019 ... ... General · Lisbon · Madrid ...     1      1     1
Jan 10, 2019 ... Our latest articles How coding...     1      1     1
Jan 18, 2019 ... Our alumni Elise tells you all...     1      1     1
Jan 18, 2019 ... Our latest articles [Testimoni...     1      1     1
Jan 18, 2019 ... by Thomas Jacquesson | Friday,...     1      1     1
Jan 30, 2019 ... Our latest articles Coding Boo...     1      1     1
... A PRÓXIMA GERAÇÃO DE CRIADORES DIGITAIS EM....     1      1     1
Jan 8, 2019 ... PREPARING THE NEXT GENERATION O...     1      1     1
Jimmy: Alright, so we are recording. Welcome ba...     1      1     1
Join Ironhack. Do you want to study at Ironhack...     1      1     1
...                                                  ...    ...   ...
Curso de UX design: em 9 semanas aprendes os fu...     1      1     1
... abiertas) – Come Visit us! Ironhack Campus ...     1      1     1
10 set. 2018 ... Mas algumas perguntas muito co...     1      1     1
13 fev. 2019 ... Como você pode mudar a sua vid...     1      1     1
2018 Campus Berlin. 2018 Campus Amsterdam. 2018...     1      1     1
990 Biscayne Blvd. Ste 503 - Miami FL 33132 © 2...     1      1     1
After Madrid, Barcelona, Miami, Paris, Mexico C...     1      1     1
Amesterdão Barcelona Berlim Bogotá Lisbon Madri...     1      1     1
Amsterdam Barcelona Berlim Bogotá Lisbon Madrid...     1      1     1
Amsterdam Barcelone Berlin Bogotá Lisbon Madrid...     1      1     1
Apr 12, 2016 ... The Ironhack Hackshow is the m...     1      1     1
Barcelona Campus. 2/5. Prev Next. Ironhack Barc...     1      1     1
Career Support. Career Support. 120 SW 8th St. ...     1      1     1
Coisas que você pode fazer com Javascript: Webs...     1      1     1
Dec 20, 2016 ... Marc, our fearless campus mana...     1      1     1
Formez vous sur Madrid en Développement Web ou ...     1      1     1
Dec 20, 2018 ... From architecture to UX/UI Des...     1      1     1
Dec 20, 2018 ... In May this year, I was at a p...     1      1     1
Dec 3, 2018 ... Our latest articles Inside Cabi...     1      1     1
Dec 3, 2018 ... PREPARING THE NEXT GENERATION O...     1      1     1
Dec 4, 2018 ... Organizer. Ironhack Berlin - Co...     1      1     1
Descubra as tendências que você, desenvolvedor ...     1      1     1
Después de 9 semanas de trabajo intensivo en el...     1      1     1
Enjoy a guided tour and discover some of the mo...     1      1     1
Feb 1, 2019 ... Organizer. Ironhack Amsterdam. ...     1      1     1
Feb 20, 2019 ... After Madrid, Barcelona, Miami...     1      1     1
First impressions count, and the window in whic...     1      1     1
For a whole day, you'll immerse yourself in the...     1      1     1
... Design grâce à nos cours à temps plein ou p...     1      1     1
por Pedro Falkenbach | Wednesday, February 13, ...     1      1     1

[72 rows x 3 columns]

In [23]:
cities_sql= """
CREATE TABLE `cities` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL UNIQUE,
  PRIMARY KEY (`id`)
  
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8;"""

In [24]:
events_sql="""
CREATE TABLE `events` (
  `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(45) NOT NULL,
  `link` varchar(45) NOT NULL,
  `snippet` varchar(45) NOT NULL,
  `city_id` smallint(5) unsigned NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_city_id` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) 
  
) ENGINE=InnoDB AUTO_INCREMENT=201 DEFAULT CHARSET=utf8;"""

In [25]:
cities_df = all_cities_df.groupby("city").count().reset_index()[['city']]

In [26]:
cities_df.rename(columns={'city':'name'}, inplace=True)

In [27]:
cities_df.reset_index(inplace=True)

In [28]:
cities_df.to_sql(name=cities, con=engine, if_exists='append', index=True)

NameError: name 'engine' is not defined

In [29]:
from sqlalchemy import create_engine
engine = create_engine('mysql+pymysql://ironhacker_read:ir0nhack3r@35.239.232.23/ironhack_events')

In [30]:
cities_df

    index         name
0       0    Amsterdam
1       1    Barcelona
2       2       Berlin
3       3       Bogotá
4       4       Lisbon
5       5       Madrid
6       6  Mexico City
7       7        Miami
8       8       Munich
9       9        Paris
10     10    São Paolo

In [31]:
import mysql.connector

In [32]:
conn = mysql.connector.connect(host='35.239.232.23', database='ironhack_events', user='ironhacker_read', password='ir0nhack3r')

In [33]:
cursor = conn.cursor()

In [34]:
insert_sql= '''
INSERT INTO cities (name) VALUES '''

In [35]:
insert_sql= '''
INSERT INTO cities (name) VALUES '''

for city in set(all_cities_df.city):
    row_sql = f"('{city}'), "
    insert_sql += row_sql
    print(insert_sql)
insert_sql = insert_sql[:-2]

INSERT INTO cities (name) VALUES ('Paris'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'), ('Lisbon'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'), ('Lisbon'), ('Miami'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'), ('Lisbon'), ('Miami'), ('Mexico City'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'), ('Lisbon'), ('Miami'), ('Mexico City'), ('Barcelona'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'), ('Lisbon'), ('Miami'), ('Mexico City'), ('Barcelona'), ('Munich'),

INSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'), ('Lisbon'), ('Miami'), ('Mexico City'), ('Barcelona'), ('Munich'), ('Berlin'),

In [36]:
insert_sql

"\nINSERT INTO cities (name) VALUES ('Paris'), ('Amsterdam'), ('Bogotá'), ('São Paolo'), ('Madrid'), ('Lisbon'), ('Miami'), ('Mexico City'), ('Barcelona'), ('Munich'), ('Berlin')"

In [60]:
cursor.execute(insert_sql)

In [61]:
conn.commit()

## The whole and cleaned process
Sometimes run a huge process can be very heavy. You can define [chunks](https://en.wikipedia.org/wiki/Chunk_(information)) (little pieces of your dataframes instead of all the dataframe). We are adding that part to the process. 

The Ironhack API allows you to define the start parameter, if you change the variable you will have another starting point in order to have different information (look at the function below).

Note: as the snippet was too long for the number of characters we defined in the db (45 characters) I needed to give more capacity to that field

In [69]:
def call_google_api(q, start, 
                    key="AIzaSyDeDEXWk7bq0r0GYzz-Pmc6dWqRGVxJ2Zc", 
                    cx="003240156206868727193:scrr7eqktoy",
                    fields="kind,items(title,link,snippet),queries(request(title,totalResults,count,startIndex))"):
    params = {"key": key, "cx": cx, "fields": fields, "q": q, "start": start}    
    return requests.get(google_api, params=params).json()

In [59]:
def save_city(city):
    for bulk in range(1, 100, 10):
        save_bulk_city(city, bulk)

In [60]:
def save_bulk_city(city, bulk):
    bulk_result = call_google_api(q=city, start=bulk)
    if "items" in bulk_result.keys():
        save_bulk(city, bulk_result)

In [61]:
def save_bulk(city, bulk_result):
    for item in bulk_result["items"]:
        save_one_item(conn, city, item)

In [62]:
def save_one_item(conn, city, item):
    save_in_city_table(conn, city, item)
    save_in_events_table(conn, city, item)

In [71]:
def save_in_city_table(conn, city, item):
    cursor = conn.cursor()
    query = f'INSERT IGNORE INTO cities (name) VALUES ("{city}")'
    cursor.execute(query)
    conn.commit()
    return cursor.rowcount

In [72]:
def save_in_events_table(conn, city, item):
    cursor = conn.cursor()
    city_id_query = f'SELECT id FROM cities where name="{city}"'
    city_id = pd.read_sql(city_id_query, conn)["id"].values[0]
    query = "INSERT INTO events (snippet, link, title, city_id) VALUES (%s, %s, %s, %s)"
    cursor.execute(query, (            
        item["snippet"], 
        item["link"],
        item["title"],
        str(city_id)
    ))
    conn.commit()
    return cursor.rowcount

In [73]:
def save_all_cities(list_cities, conn):
    for city in list_cities:
        save_city(city)

In [74]:
conn = mysql.connector.connect(host='35.239.232.23', database='ironhack_events', user='ironhacker_read', password='ir0nhack3r')
save_all_cities(cities, conn)

DataError: 1406 (22001): Data too long for column 'link' at row 1